sh ./add_script.sh add_ppa.sh add_ppa
sh ./add_script.sh add_ppa.sh add_ppa 
sh ./add_script.sh add_script.sh add_script
sh ./add_script.sh add_script.sh add_script 
sh ./add_script.sh check_avaliable_pkg_ver.sh check_avaliable_pkg_ver
sh ./add_script.sh check_avaliable_pkg_ver.sh check_avaliable_pkg_ver 
sh ./add_script.sh check_installed_pkg_ver.sh check_installed_pkg_ver
sh ./add_script.sh check_installed_pkg_ver.sh check_installed_pkg_ver 
sh ./add_script.sh compile_cpp_opencv.sh compile_cpp_opencv
sh ./add_script.sh compile_cpp_opencv.sh compile_cpp_opencv 
sh ./add_script.sh gcc_linkerlib_path.sh gcc_linkerlib_path
sh ./add_script.sh gcc_linkerlib_path.sh gcc_linkerlib_path 
sh ./add_script.sh python_cprofile.sh python_cprofile
sh ./add_script.sh python_cprofile.sh python_cprofile 
sh ./add_script.sh remove_ppa.sh remove_ppa
sh ./add_script.sh remove_ppa.sh remove_ppa 
sh ./add_script.sh start_tightvncserver.sh start_tightvncserver
sh ./add_script.sh start_tightvncserver.sh start_tightvncserver 
sh ./add_script.sh stop_tightvncserver.sh stop_tightvncserver
sh ./add_script.sh stop_tightvncserver.sh stop_tightvncserver 
sh ./add_script.sh untar_file.sh untar_file
sh ./add_script.sh untar_file.sh untar_file 
sh ./add_script.sh upgrade_single_pkg.sh upgrade_single_pkg
sh ./add_script.sh upgrade_single_pkg.sh upgrade_single_pkg 
